homePanelUI <- function(id) {
  ns <- NS(id)
  tagList(
    fluidRow(
      box(
        title = "Welcome to MS Data Explorer App!", width = 12, status = "primary",
        HTML("<b>MS Data Explorer App</b> provides an interactive interface for effective visualization of
                expression count data sets generated by the <i> Analysis Pipeline </i>.")

      )
    ),
    fluidRow(
      box(
        title = "Load", width = 4, status = "warning",
        p("Load the xls dataset generated by your pipeline. The file should contain two sheets,
        the first should be expression
          matrix and the second sheet should contain the sample information.")
      ),
      box(
        title = "Heat Map", width = 4, status = "warning",
        p("The data is displayed in a grid where each row represents a gene and each column represents a sample.")
      ),
      box(
        title = "Cosine Similarity Plot", width = 4, status = "warning",
        p("Triangular heatmap of the cosine similarity scores across samples.")
      )
    ),
    fluidRow(
      box(
        title = "Upset Plot", width = 4, status = "warning",
        p("Plots the intersection of multiple sample sets.")
      ),
      box(
        title = "Volcano Plot", width = 4,status = "warning",
        p("A scatterplot that shows statistical significance (P value) versus magnitude of change (fold change).
          It enables quick visual identification of genes with large fold changes that are also statistically significant.")
      ),
      box(
        title = "Dim Reduction", width = 4,status = "warning",
        p("This module provides an interface to project high dimensional data
          to a lower dimension.")
      )
    ),
    fluidRow(
      box(
        title = "Authors", width = 6, status = "success",
        h5("Ellen Casavant, Sri Paladugu")
      ),
      box(title = 'Maintainer', width = 6, status = "success", h5("Sumedh Sankhe"))
    )
  )
}
